data_name: 'LatticeModulus'
data_path: '/home/jianpengc/datasets/metamaterial/LatticeModulus' #'D:\项目\Material design\code_data\data\LatticeModulus'  #ini '/home/jianpengc/datasets/metamaterial/LatticeModulus'
data_seed: 42
train_size: 8000 # 0.7 11696.3 #ini 8000
valid_size: 2000
pred_property: 'young'



wandb_args:
  use_wandb: false
  entity: "jianpengc"
  project: "metabench"
  save_name: 'uni_truss-uni_prop'



output_dir: './checkpoints/uni_truss/uni'
log_dir: './logs/uni_truss/uni'
gen_path: './results/uni_truss'

model:
  numNodes: 500
  dim: 12
  ax_dim: 32
  a_dim: 8
  x_dim: 8
#  latent_dim: &latent_dim 48 # # ax_dim + x_dim + a_dim
#  z_dim: *latent_dim

#  c_hidden_dim: [ *latent_dim, 400, 800, 1000, 400, 400, 200 ]
#  inv_hidden_dim: [500, 500, 600, 500, 300, 200]
  output_dim: 12
  add_noise: False

training:
  epochs: 10000
  patience: 50
  batch_size: 100
  val_check_interval: 10

  test_batch_size: 1  # do not change
  valid_batch_size: 1   # do not change
  dropout: 0.0
  kl_update: "annealing"
  recon_loss_func: "l2"

optimizer:
  learning_rate: 0.0005
  c_lr: 0.001
  inv_lr: 0.0001

loss_weights:
  x_weight: 1.0
  c_weight: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
